default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 
  host: localhost

development:
  <<: *default
  database: sson_development

test:
  <<: *default
  database: sson_test